services:
  app_proxy:
    environment:
      APP_HOST: airsonic
      APP_PORT: 4040
      PROXY_AUTH_ADD: "false"

  server:
    image: airsonic/airsonic:latest
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ${UMBREL_ROOT}/data/storage/downloads/music:/music
